insert into categories (name, slug, type)
values
  ('Infra Cloud', 'infra-cloud', 'expense'),
  ('SaaS / Suscripciones', 'saas-suscripciones', 'expense'),
  ('Marketing', 'marketing', 'expense'),
  ('Comisiones bancarias', 'comisiones-bancarias', 'financial'),
  ('Intereses', 'intereses', 'financial'),
  ('Impuestos / SS', 'impuestos-ss', 'expense'),
  ('Transferencias', 'transferencias', 'transfer'),
  ('Nominas', 'nominas', 'income'),
  ('Seguros', 'seguros', 'expense'),
  ('Prestamos', 'prestamos', 'financial'),
  ('Servicios profesionales', 'servicios-profesionales', 'expense'),
  ('Suministros', 'suministros', 'expense'),
  ('Telecomunicaciones', 'telecomunicaciones', 'expense'),
  ('Alimentacion', 'alimentacion', 'expense'),
  ('Viajes', 'viajes', 'expense'),
  ('Compras', 'compras', 'expense'),
  ('Salud y Fitness', 'salud-fitness', 'expense'),
  ('Comunidad', 'comunidad', 'expense')
on conflict (slug) do update
  set name = excluded.name,
      type = excluded.type;

delete from category_rules
where user_id is null
  and name in (
    'Infra Cloud: AWS',
    'Infra Cloud: LINODE',
    'Infra Cloud: AKAMAI',
    'SaaS: OPENAI',
    'SaaS: CHATGPT',
    'Marketing: LINKEDIN',
    'Marketing: SORTLIST',
    'Comisiones bancarias: COMISION',
    'Intereses: INTERESES',
    'Impuestos/SS: TGSS',
    'Impuestos/SS: HACIENDA',
    'Transferencias: TRANSFERENCIA',
    'Nominas: NOMINA',
    'Impuestos/SS: IMPUESTOS',
    'Impuestos/SS: SEGUROS SOCIALES',
    'Prestamos: PRESTAMO',
    'Seguros: SEGURO',
    'Seguros: ASEGURADORA',
    'Servicios profesionales: ASESOR',
    'Suministros: AGUA',
    'Suministros: LUZ',
    'Suministros: ELECTRICIDAD',
    'Suministros: GAS',
    'Suministros: ENERGIA',
    'Telecomunicaciones: TELEFONO',
    'Telecomunicaciones: INTERNET',
    'Telecomunicaciones: FIBRA',
    'Alimentacion: SUPERMERCADO',
    'Alimentacion: ALIMENTACION',
    'Viajes: VUELO',
    'Viajes: HOTEL',
    'Salud y Fitness: GIMNASIO',
    'Salud y Fitness: GYM',
    'Comunidad: COMUNIDAD'
  );

insert into category_rules (
  user_id,
  name,
  priority,
  match_field,
  match_type,
  pattern,
  txn_type_filter,
  category_id,
  confidence
)
select
  null,
  rule.name,
  rule.priority,
  rule.match_field,
  rule.match_type,
  rule.pattern,
  rule.txn_type_filter,
  categories.id,
  rule.confidence
from (
  values
    ('Infra Cloud: AWS', 100, 'merchant_normalized'::category_match_field, 'contains'::category_match_type, 'AWS', null::text[], 'infra-cloud', 0.9),
    ('Infra Cloud: LINODE', 100, 'merchant_normalized'::category_match_field, 'contains'::category_match_type, 'LINODE', null::text[], 'infra-cloud', 0.9),
    ('Infra Cloud: AKAMAI', 100, 'merchant_normalized'::category_match_field, 'contains'::category_match_type, 'AKAMAI', null::text[], 'infra-cloud', 0.9),
    ('SaaS: OPENAI', 90, 'merchant_normalized'::category_match_field, 'contains'::category_match_type, 'OPENAI', null::text[], 'saas-suscripciones', 0.9),
    ('SaaS: CHATGPT', 90, 'merchant_normalized'::category_match_field, 'contains'::category_match_type, 'CHATGPT', null::text[], 'saas-suscripciones', 0.9),
    ('Marketing: LINKEDIN', 90, 'merchant_normalized'::category_match_field, 'contains'::category_match_type, 'LINKEDIN', null::text[], 'marketing', 0.9),
    ('Marketing: SORTLIST', 90, 'merchant_normalized'::category_match_field, 'contains'::category_match_type, 'SORTLIST', null::text[], 'marketing', 0.9),
    ('Comisiones bancarias: COMISION', 80, 'description_clean'::category_match_field, 'contains'::category_match_type, 'COMISION', array['fee'], 'comisiones-bancarias', 0.95),
    ('Intereses: INTERESES', 80, 'description_clean'::category_match_field, 'contains'::category_match_type, 'INTERESES', array['interest'], 'intereses', 0.95),
    ('Impuestos/SS: TGSS', 80, 'description_clean'::category_match_field, 'contains'::category_match_type, 'TGSS', array['tax'], 'impuestos-ss', 0.95),
    ('Impuestos/SS: HACIENDA', 80, 'description_clean'::category_match_field, 'contains'::category_match_type, 'HACIENDA', array['tax'], 'impuestos-ss', 0.95),
    ('Transferencias: TRANSFERENCIA', 70, 'description_clean'::category_match_field, 'starts_with'::category_match_type, 'TRANSFERENCIA', array['transfer'], 'transferencias', 0.9),
    ('Nominas: NOMINA', 95, 'description_clean'::category_match_field, 'starts_with'::category_match_type, 'NOMINA', array['income'], 'nominas', 0.95),
    ('Impuestos/SS: IMPUESTOS', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'IMPUEST', null::text[], 'impuestos-ss', 0.9),
    ('Impuestos/SS: SEGUROS SOCIALES', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'SEGUROS SOCIALES', null::text[], 'impuestos-ss', 0.9),
    ('Prestamos: PRESTAMO', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'PRESTAMO', null::text[], 'prestamos', 0.9),
    ('Seguros: SEGURO', 90, 'description_clean'::category_match_field, 'contains'::category_match_type, 'SEGURO', null::text[], 'seguros', 0.9),
    ('Seguros: ASEGURADORA', 90, 'description_clean'::category_match_field, 'contains'::category_match_type, 'ASEGURADORA', null::text[], 'seguros', 0.9),
    ('Servicios profesionales: ASESOR', 85, 'merchant_normalized'::category_match_field, 'contains'::category_match_type, 'ASESOR', null::text[], 'servicios-profesionales', 0.9),
    ('Suministros: AGUA', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'AGUA', null::text[], 'suministros', 0.9),
    ('Suministros: LUZ', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'LUZ', null::text[], 'suministros', 0.85),
    ('Suministros: ELECTRICIDAD', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'ELECTRIC', null::text[], 'suministros', 0.85),
    ('Suministros: GAS', 80, 'description_clean'::category_match_field, 'regex'::category_match_type, '(^|\\s)GAS(\\s|$)', null::text[], 'suministros', 0.85),
    ('Suministros: ENERGIA', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'ENERG', null::text[], 'suministros', 0.85),
    ('Telecomunicaciones: TELEFONO', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'TELEF', null::text[], 'telecomunicaciones', 0.85),
    ('Telecomunicaciones: INTERNET', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'INTERNET', null::text[], 'telecomunicaciones', 0.85),
    ('Telecomunicaciones: FIBRA', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'FIBRA', null::text[], 'telecomunicaciones', 0.85),
    ('Alimentacion: SUPERMERCADO', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'SUPERMERC', null::text[], 'alimentacion', 0.85),
    ('Alimentacion: ALIMENTACION', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'ALIMENT', null::text[], 'alimentacion', 0.85),
    ('Viajes: VUELO', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'VUELO', null::text[], 'viajes', 0.85),
    ('Viajes: HOTEL', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'HOTEL', null::text[], 'viajes', 0.85),
    ('Salud y Fitness: GIMNASIO', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'GIMNASIO', null::text[], 'salud-fitness', 0.85),
    ('Salud y Fitness: GYM', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'GYM', null::text[], 'salud-fitness', 0.85),
    ('Comunidad: COMUNIDAD', 80, 'description_clean'::category_match_field, 'contains'::category_match_type, 'COMUNIDAD', null::text[], 'comunidad', 0.85)
) as rule(name, priority, match_field, match_type, pattern, txn_type_filter, category_slug, confidence)
join categories on categories.slug = rule.category_slug;
