insert into categories (name, slug, type)
values
  ('Infra Cloud', 'infra-cloud', 'expense'),
  ('SaaS / Suscripciones', 'saas-suscripciones', 'expense'),
  ('Marketing', 'marketing', 'expense'),
  ('Comisiones bancarias', 'comisiones-bancarias', 'financial'),
  ('Intereses', 'intereses', 'financial'),
  ('Impuestos / SS', 'impuestos-ss', 'expense'),
  ('Transferencias', 'transferencias', 'transfer'),
  ('Nominas', 'nominas', 'income'),
  ('Seguros', 'seguros', 'expense'),
  ('Prestamos', 'prestamos', 'financial'),
  ('Servicios profesionales', 'servicios-profesionales', 'expense'),
  ('Suministros', 'suministros', 'expense'),
  ('Telecomunicaciones', 'telecomunicaciones', 'expense'),
  ('Alimentacion', 'alimentacion', 'expense'),
  ('Viajes', 'viajes', 'expense'),
  ('Compras', 'compras', 'expense'),
  ('Salud y Fitness', 'salud-fitness', 'expense'),
  ('Comunidad', 'comunidad', 'expense'),
  ('Restauracion / Ocio', 'restauracion-ocio', 'expense')
on conflict (slug) do update
  set name = excluded.name,
      type = excluded.type;

delete from category_rules
where user_id is null
  and name in (
    'Infra Cloud: AWS',
    'Infra Cloud: LINODE',
    'Infra Cloud: AKAMAI',
    'SaaS: OPENAI',
    'SaaS: CHATGPT',
    'Marketing: LINKEDIN',
    'Marketing: SORTLIST',
    'Comisiones bancarias: COMISION',
    'Comisiones bancarias: CUOTA ANUAL',
    'Comisiones bancarias: MANTENIMIENTO',
    'Intereses: INTERESES',
    'Impuestos/SS: TGSS',
    'Impuestos/SS: HACIENDA',
    'Impuestos/SS: AEAT',
    'Impuestos/SS: IBI',
    'Impuestos/SS: AYUNTAMIENTO',
    'Transferencias: TRANSFERENCIA',
    'Transferencias: TRANS INM',
    'Transferencias: TRASPASO',
    'Nominas: NOMINA',
    'Impuestos/SS: IMPUESTOS',
    'Impuestos/SS: SEGUROS SOCIALES',
    'Prestamos: PRESTAMO',
    'Prestamos: HIPOTECA',
    'Prestamos: CUOTA PTMO',
    'Prestamos: AMORTIZACION',
    'Seguros: SEGURO',
    'Seguros: ASEGURADORA',
    'Servicios profesionales: ASESOR',
    'Suministros: AGUA',
    'Suministros: LUZ',
    'Suministros: ELECTRICIDAD',
    'Suministros: GAS',
    'Suministros: ENERGIA',
    'Suministros: IBERDROLA',
    'Suministros: ENDESA',
    'Suministros: NATURGY',
    'Suministros: CANAL ISABEL',
    'Suministros: AQUALIA',
    'Suministros: BASURA',
    'Telecomunicaciones: TELEFONO',
    'Telecomunicaciones: INTERNET',
    'Telecomunicaciones: FIBRA',
    'Telecomunicaciones: MOVISTAR',
    'Telecomunicaciones: VODAFONE',
    'Telecomunicaciones: ORANGE',
    'Telecomunicaciones: YOIGO',
    'Telecomunicaciones: DIGI',
    'Telecomunicaciones: JAZZTEL',
    'Telecomunicaciones: MASMOVIL',
    'Alimentacion: SUPERMERCADO',
    'Alimentacion: ALIMENTACION',
    'Viajes: VUELO',
    'Viajes: HOTEL',
    'Viajes: Movilidad',
    'Salud y Fitness: GIMNASIO',
    'Salud y Fitness: GYM',
    'Comunidad: COMUNIDAD',
    'Alimentacion: MERCADONA',
    'Alimentacion: CARREFOUR',
    'Alimentacion: LIDL',
    'Alimentacion: ALDI',
    'Alimentacion: CONSUM',
    'Alimentacion: EROSKI',
    'SaaS: HOTMART',
    'SaaS: Streaming',
    'SaaS: Cloud',
    'SaaS: Productivity',
    'Restauracion/Ocio: Cafes y bares',
    'Restauracion/Ocio: Restaurantes',
    'Restauracion/Ocio: Heladerias',
    'Restauracion/Ocio: Dulces'
  );

insert into category_rules (
  user_id,
  name,
  priority,
  is_active,
  match_field,
  match_type,
  pattern,
  txn_type_filter,
  category_id,
  confidence
)
select
  null,
  rule.name,
  rule.priority,
  true,
  rule.match_field,
  rule.match_type,
  rule.pattern,
  rule.txn_type_filter,
  categories.id,
  rule.confidence
from (
  values
    ('Infra Cloud: AWS', 100, 'merchant_normalized'::category_match_field, 'contains'::category_match_type, 'AWS', null::text[], 'infra-cloud', 0.9),
    ('Infra Cloud: LINODE', 100, 'merchant_normalized'::category_match_field, 'contains'::category_match_type, 'LINODE', null::text[], 'infra-cloud', 0.9),
    ('Infra Cloud: AKAMAI', 100, 'merchant_normalized'::category_match_field, 'contains'::category_match_type, 'AKAMAI', null::text[], 'infra-cloud', 0.9),
    ('SaaS: OPENAI', 90, 'merchant_normalized'::category_match_field, 'contains'::category_match_type, 'OPENAI', null::text[], 'saas-suscripciones', 0.9),
    ('SaaS: CHATGPT', 90, 'merchant_normalized'::category_match_field, 'contains'::category_match_type, 'CHATGPT', null::text[], 'saas-suscripciones', 0.9),
    ('Marketing: LINKEDIN', 90, 'merchant_normalized'::category_match_field, 'contains'::category_match_type, 'LINKEDIN', null::text[], 'marketing', 0.9),
    ('Marketing: SORTLIST', 90, 'merchant_normalized'::category_match_field, 'contains'::category_match_type, 'SORTLIST', null::text[], 'marketing', 0.9),
    ('Comisiones bancarias: COMISION', 80, 'description_clean'::category_match_field, 'contains'::category_match_type, 'COMISION', array['fee'], 'comisiones-bancarias', 0.95),
    ('Comisiones bancarias: CUOTA ANUAL', 75, 'description_clean'::category_match_field, 'contains'::category_match_type, 'CUOTA ANUAL', null::text[], 'comisiones-bancarias', 0.9),
    ('Comisiones bancarias: MANTENIMIENTO', 75, 'description_clean'::category_match_field, 'regex'::category_match_type, 'MANTENIMIENTO\\s+(CUENTA|TARJETA)', null::text[], 'comisiones-bancarias', 0.9),
    ('Intereses: INTERESES', 80, 'description_clean'::category_match_field, 'contains'::category_match_type, 'INTERESES', array['interest'], 'intereses', 0.95),
    ('Impuestos/SS: TGSS', 80, 'description_clean'::category_match_field, 'contains'::category_match_type, 'TGSS', array['tax'], 'impuestos-ss', 0.95),
    ('Impuestos/SS: HACIENDA', 80, 'description_clean'::category_match_field, 'contains'::category_match_type, 'HACIENDA', array['tax'], 'impuestos-ss', 0.95),
    ('Impuestos/SS: AEAT', 80, 'description_clean'::category_match_field, 'contains'::category_match_type, 'AEAT', null::text[], 'impuestos-ss', 0.95),
    ('Impuestos/SS: IBI', 80, 'description_clean'::category_match_field, 'contains'::category_match_type, 'IBI', null::text[], 'impuestos-ss', 0.9),
    ('Impuestos/SS: AYUNTAMIENTO', 75, 'description_clean'::category_match_field, 'contains'::category_match_type, 'AYUNTAMIENTO', null::text[], 'impuestos-ss', 0.85),
    ('Transferencias: TRANSFERENCIA', 70, 'description_clean'::category_match_field, 'starts_with'::category_match_type, 'TRANSFERENCIA', array['transfer'], 'transferencias', 0.9),
    ('Transferencias: TRANS INM', 70, 'description_clean'::category_match_field, 'contains'::category_match_type, 'TRANS INM', null::text[], 'transferencias', 0.9),
    ('Transferencias: TRASPASO', 70, 'description_clean'::category_match_field, 'contains'::category_match_type, 'TRASPASO', null::text[], 'transferencias', 0.9),
    ('Nominas: NOMINA', 95, 'description_clean'::category_match_field, 'starts_with'::category_match_type, 'NOMINA', array['income'], 'nominas', 0.95),
    ('Impuestos/SS: IMPUESTOS', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'IMPUEST', null::text[], 'impuestos-ss', 0.9),
    ('Impuestos/SS: SEGUROS SOCIALES', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'SEGUROS SOCIALES', null::text[], 'impuestos-ss', 0.9),
    ('Prestamos: PRESTAMO', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'PRESTAMO', null::text[], 'prestamos', 0.9),
    ('Prestamos: HIPOTECA', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'HIPOTECA', null::text[], 'prestamos', 0.9),
    ('Prestamos: CUOTA PTMO', 85, 'description_clean'::category_match_field, 'regex'::category_match_type, 'CUOTA\\s*PTMO', null::text[], 'prestamos', 0.9),
    ('Prestamos: AMORTIZACION', 80, 'description_clean'::category_match_field, 'contains'::category_match_type, 'AMORTIZACION', null::text[], 'prestamos', 0.85),
    ('Seguros: SEGURO', 90, 'description_clean'::category_match_field, 'contains'::category_match_type, 'SEGURO', null::text[], 'seguros', 0.9),
    ('Seguros: ASEGURADORA', 90, 'description_clean'::category_match_field, 'contains'::category_match_type, 'ASEGURADORA', null::text[], 'seguros', 0.9),
    ('Servicios profesionales: ASESOR', 85, 'merchant_normalized'::category_match_field, 'contains'::category_match_type, 'ASESOR', null::text[], 'servicios-profesionales', 0.9),
    ('Suministros: AGUA', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'AGUA', null::text[], 'suministros', 0.9),
    ('Suministros: LUZ', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'LUZ', null::text[], 'suministros', 0.85),
    ('Suministros: ELECTRICIDAD', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'ELECTRIC', null::text[], 'suministros', 0.85),
    ('Suministros: GAS', 80, 'description_clean'::category_match_field, 'regex'::category_match_type, '(^|\\s)GAS(\\s|$)', null::text[], 'suministros', 0.85),
    ('Suministros: ENERGIA', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'ENERG', null::text[], 'suministros', 0.85),
    ('Suministros: IBERDROLA', 90, 'description_clean'::category_match_field, 'contains'::category_match_type, 'IBERDROLA', null::text[], 'suministros', 0.9),
    ('Suministros: ENDESA', 90, 'description_clean'::category_match_field, 'contains'::category_match_type, 'ENDESA', null::text[], 'suministros', 0.9),
    ('Suministros: NATURGY', 90, 'description_clean'::category_match_field, 'contains'::category_match_type, 'NATURGY', null::text[], 'suministros', 0.9),
    ('Suministros: CANAL ISABEL', 85, 'description_clean'::category_match_field, 'regex'::category_match_type, 'CANAL\\s+ISABEL', null::text[], 'suministros', 0.85),
    ('Suministros: AQUALIA', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'AQUALIA', null::text[], 'suministros', 0.85),
    ('Suministros: BASURA', 80, 'description_clean'::category_match_field, 'regex'::category_match_type, '\\b(BASURA|RESIDUOS)\\b', null::text[], 'suministros', 0.85),
    ('Telecomunicaciones: TELEFONO', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'TELEF', null::text[], 'telecomunicaciones', 0.85),
    ('Telecomunicaciones: INTERNET', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'INTERNET', null::text[], 'telecomunicaciones', 0.85),
    ('Telecomunicaciones: FIBRA', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'FIBRA', null::text[], 'telecomunicaciones', 0.85),
    ('Telecomunicaciones: MOVISTAR', 90, 'description_clean'::category_match_field, 'contains'::category_match_type, 'MOVISTAR', null::text[], 'telecomunicaciones', 0.9),
    ('Telecomunicaciones: VODAFONE', 90, 'description_clean'::category_match_field, 'contains'::category_match_type, 'VODAFONE', null::text[], 'telecomunicaciones', 0.9),
    ('Telecomunicaciones: ORANGE', 90, 'description_clean'::category_match_field, 'contains'::category_match_type, 'ORANGE', null::text[], 'telecomunicaciones', 0.9),
    ('Telecomunicaciones: YOIGO', 90, 'description_clean'::category_match_field, 'contains'::category_match_type, 'YOIGO', null::text[], 'telecomunicaciones', 0.9),
    ('Telecomunicaciones: DIGI', 90, 'description_clean'::category_match_field, 'contains'::category_match_type, 'DIGI', null::text[], 'telecomunicaciones', 0.9),
    ('Telecomunicaciones: JAZZTEL', 90, 'description_clean'::category_match_field, 'contains'::category_match_type, 'JAZZTEL', null::text[], 'telecomunicaciones', 0.9),
    ('Telecomunicaciones: MASMOVIL', 90, 'description_clean'::category_match_field, 'contains'::category_match_type, 'MASMOVIL', null::text[], 'telecomunicaciones', 0.9),
    ('Alimentacion: SUPERMERCADO', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'SUPERMERC', null::text[], 'alimentacion', 0.85),
    ('Alimentacion: ALIMENTACION', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'ALIMENT', null::text[], 'alimentacion', 0.85),
    ('Viajes: VUELO', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'VUELO', null::text[], 'viajes', 0.85),
    ('Viajes: HOTEL', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'HOTEL', null::text[], 'viajes', 0.85),
    ('Viajes: Movilidad', 80, 'description_clean'::category_match_field, 'regex'::category_match_type, '\\b(UBER|CABIFY|BOLT|TAXI|VTC|PARKING|APARCAMIENTO|PEAJE|AUTOPISTA|METRO|RENFE|ALSA|AVANZA|EMT|BUS|TREN|TRANVIA|BLABLACAR)\\b', null::text[], 'viajes', 0.85),
    ('Salud y Fitness: GIMNASIO', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'GIMNASIO', null::text[], 'salud-fitness', 0.85),
    ('Salud y Fitness: GYM', 85, 'description_clean'::category_match_field, 'contains'::category_match_type, 'GYM', null::text[], 'salud-fitness', 0.85),
    ('Comunidad: COMUNIDAD', 80, 'description_clean'::category_match_field, 'contains'::category_match_type, 'COMUNIDAD', null::text[], 'comunidad', 0.85),
    ('Alimentacion: MERCADONA', 90, 'description_clean'::category_match_field, 'contains'::category_match_type, 'MERCADONA', null::text[], 'alimentacion', 0.9),
    ('Alimentacion: CARREFOUR', 90, 'description_clean'::category_match_field, 'contains'::category_match_type, 'CARREFOUR', null::text[], 'alimentacion', 0.9),
    ('Alimentacion: LIDL', 90, 'description_clean'::category_match_field, 'contains'::category_match_type, 'LIDL', null::text[], 'alimentacion', 0.9),
    ('Alimentacion: ALDI', 90, 'description_clean'::category_match_field, 'contains'::category_match_type, 'ALDI', null::text[], 'alimentacion', 0.9),
    ('Alimentacion: CONSUM', 90, 'description_clean'::category_match_field, 'contains'::category_match_type, 'CONSUM', null::text[], 'alimentacion', 0.9),
    ('Alimentacion: EROSKI', 90, 'description_clean'::category_match_field, 'contains'::category_match_type, 'EROSKI', null::text[], 'alimentacion', 0.9),
    ('SaaS: HOTMART', 90, 'description_clean'::category_match_field, 'contains'::category_match_type, 'HOTMART', null::text[], 'saas-suscripciones', 0.9),
    ('SaaS: Streaming', 80, 'description_clean'::category_match_field, 'regex'::category_match_type, '\\b(NETFLIX|SPOTIFY|HBO\\s*MAX|HBO|DISNEY|PRIME\\s*VIDEO|AMAZON\\s*PRIME|DAZN)\\b', null::text[], 'saas-suscripciones', 0.85),
    ('SaaS: Cloud', 80, 'description_clean'::category_match_field, 'regex'::category_match_type, '\\b(GOOGLE\\s*ONE|ICLOUD|DROPBOX|ONEDRIVE)\\b', null::text[], 'saas-suscripciones', 0.85),
    ('SaaS: Productivity', 80, 'description_clean'::category_match_field, 'regex'::category_match_type, '\\b(MICROSOFT\\s*365|OFFICE\\s*365)\\b', null::text[], 'saas-suscripciones', 0.85),
    ('Restauracion/Ocio: Cafes y bares', 75, 'description_clean'::category_match_field, 'regex'::category_match_type, '\\b(CAFE|COFFEE|CAFETERIA|BAR|PUB|CLUB)\\b', null::text[], 'restauracion-ocio', 0.82),
    ('Restauracion/Ocio: Restaurantes', 75, 'description_clean'::category_match_field, 'regex'::category_match_type, '\\b(RESTAURANTE|MESON|TABERNA|PIZZA|BURGER|TAPAS|ASADOR|PARRILLA|BRASERIA)\\b', null::text[], 'restauracion-ocio', 0.82),
    ('Restauracion/Ocio: Heladerias', 75, 'description_clean'::category_match_field, 'regex'::category_match_type, '\\b(GELATO|HELAD|HELADERIA)\\b', null::text[], 'restauracion-ocio', 0.82),
    ('Restauracion/Ocio: Dulces', 70, 'description_clean'::category_match_field, 'contains'::category_match_type, 'DULCE DE LECHE', null::text[], 'restauracion-ocio', 0.82)
) as rule(name, priority, match_field, match_type, pattern, txn_type_filter, category_slug, confidence)
join categories on categories.slug = rule.category_slug;
